### ISSUE TITLE
Jenkins console output no errors but it mark it as failed ?

### ISSUE THREAD

**Issue by Iliyass** [drawmyattention/laravel-jenkins-ci-boilerplate#2]
Hi man, I have used your `build.xml` and build directory on my laravel existing project, I have setup the jenkins, and all good, but when I start the build the console outputs no errors but it still tells me that it's failed that's the console output http://pastebin.com/ihpEuc58

Can you please help me out ? 
btw how can I add to the build some artisan commands like serve or migrate to be a part of the build is that possible ? 

Thank you for this repo.

**Comment by Javier-Rotelli** [comment]
I had the same issue. here is the cause:

```
[phpunit] Warning:    The Xdebug extension is not loaded
[phpunit]             No code coverage will be generated.
```

just install xdebug on your CI server and it should work

**Comment by amochohan** [comment]
Correct. You will need to install the XDebug extension to run code coverage.
