### ISSUE TITLE
Unable to Generate Coverage

### ISSUE THREAD

**Issue by fobus42** [drawmyattention/laravel-jenkins-ci-boilerplate#4]
Hi,

Every think works great except of coverage. I'm getting this error : 

phpunit:
  [phpunit] PHPUnit 5.6.1 by Sebastian Bergmann and contributors.
  [phpunit] 
  [phpunit] Error:         No whitelist configured, no code coverage will be generated
  [phpunit] 
  [phpunit] .                                                                   1 / 1 (100%)
  [phpunit] 
  [phpunit] Time: 345 ms, Memory: 18.00MB
  [phpunit] 
  [phpunit] OK (1 test, 1 assertion)

What can we do about that?

**Comment by amochohan** [comment]
The answer looks like it's provided in your message:

    [phpunit] Error: No whitelist configured, no code coverage will be generated
